package com.myspace.pollution.pollution_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Alert implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label("message")
	private java.lang.String message;
	@org.kie.api.definition.type.Label("ts")
	private java.util.Date ts;

	@org.kie.api.definition.type.Label(value = "severity")
	private java.lang.String severity;

	@org.kie.api.definition.type.Label(value = "source")
	private java.lang.String source;
	
	@org.kie.api.definition.type.Label(value = "locationId")
	private java.lang.String locationId;
        @org.kie.api.definition.type.Label(value = "co")
        private java.lang.Double co;
        @org.kie.api.definition.type.Label(value = "co2")
        private java.lang.Double co2;
        @org.kie.api.definition.type.Label(value = "co3")
        private java.lang.Double co3;
        @org.kie.api.definition.type.Label(value = "co5")
        private java.lang.Double co5;
        @org.kie.api.definition.type.Label(value = "co6")
        private java.lang.Double co6;
        @org.kie.api.definition.type.Label(value = "co7")
        private java.lang.Double co7;
        @org.kie.api.definition.type.Label(value = "co9")
        private java.lang.Double co9;








	public Alert() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public java.util.Date getTs() {
		return this.ts;
	}

	public void setTs(java.util.Date ts) {
		this.ts = ts;
	}

	public java.lang.String getSeverity() {
		return this.severity;
	}

	public void setSeverity(java.lang.String severity) {
		this.severity = severity;
	}

	public java.lang.String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(java.lang.String locationId) {
		this.locationId = locationId;
	}

	public Alert(java.lang.String type, java.lang.String message,
			java.util.Date ts, java.lang.String severity,
			java.lang.String locationId) {
		this.type = type;
		this.message = message;
		this.ts = ts;
		this.severity = severity;
		this.locationId = locationId;
	}


        public java.lang.Double getCo() {
                return this.co;
        }

        public void setCo(java.lang.Double co) {
                this.co = co;
        }


        public java.lang.Double getCo2() {
                return this.co2;
        }

        public void setCo2(java.lang.Double co2) {
                this.co2 = co2;
        }


        public java.lang.Double getCo3() {
                return this.co3;
        }

        public void setCo3(java.lang.Double co3) {
                this.co3 = co3;
        }


        public java.lang.Double getCo5() {
                return this.co5;
        }

        public void setCo5(java.lang.Double co5) {
                this.co5 = co5;
        }


        public java.lang.Double getCo6() {
                return this.co6;
        }

        public void setCo6(java.lang.Double co6) {
                this.co6 = co6;
        }


        public java.lang.Double getCo7() {
                return this.co7;
        }

        public void setCo7(java.lang.Double co7) {
                this.co7 = co7;
        }


        public java.lang.Double getCo9() {
                return this.co9;
        }

        public void setCo9(java.lang.Double co9) {
                this.co9 = co9;
        }

}