package com.myspace.pollution.pollution_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SensorReading implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	@org.kie.api.definition.type.Label("co2")
	private java.lang.Double co2;
	@org.kie.api.definition.type.Label("sensorId")
	private java.lang.String sensorId;
	@org.kie.api.definition.type.Label("locationId")
	private java.lang.String locationId;
	@org.kie.api.definition.type.Label("pm25")
	private java.lang.Double pm25;
	@org.kie.api.definition.type.Label("ts")
	private java.util.Date ts;

	@org.kie.api.definition.type.Label("pm1")
	private java.lang.Double pm1;

	@org.kie.api.definition.type.Label("pm10")
	private java.lang.Double pm10;

	@org.kie.api.definition.type.Label("temperature")
	private java.lang.Double temperature;

	@org.kie.api.definition.type.Label("humidity")
	private java.lang.Double humidity;

	@org.kie.api.definition.type.Label("hourOfDay")
	private java.lang.Integer hourOfDay;

	@org.kie.api.definition.type.Label("dayOfWeek")
	private java.lang.Integer dayOfWeek;

	@org.kie.api.definition.type.Label("monthOfYear")
	private java.lang.Integer monthOfYear;

	@org.kie.api.definition.type.Label("shift")
	private String shift;
   
	@org.kie.api.definition.type.Label(value = "co3")
    private java.lang.Double co3;
        @org.kie.api.definition.type.Label(value = "co4")
        private java.lang.Double co4;


	
	public SensorReading() {
	}
	public java.lang.Double getCo2() {
		return this.co2;
	}

	public void setCo2(java.lang.Double co2) {
		this.co2 = co2;
	}
	public java.lang.String getSensorId() {
		return this.sensorId;
	}

	public void setSensorId(java.lang.String sensorId) {
		this.sensorId = sensorId;
	}

	public java.lang.String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(java.lang.String locationId) {
		this.locationId = locationId;
	}

	public java.lang.Double getPm25() {
		return this.pm25;
	}

	public void setPm25(java.lang.Double pm25) {
		this.pm25 = pm25;
	}

	public java.util.Date getTs() {
		return this.ts;
	}

	public void setTs(java.util.Date ts) {
		this.ts = ts;
	}

	public java.lang.Double getPm1() {
		return this.pm1;
	}

	public void setPm1(java.lang.Double pm1) {
		this.pm1 = pm1;
	}

	public java.lang.Double getPm10() {
		return this.pm10;
	}

	public void setPm10(java.lang.Double pm10) {
		this.pm10 = pm10;
	}

	public java.lang.Double getTemperature() {
		return this.temperature;
	}

	public void setTemperature(java.lang.Double temperature) {
		this.temperature = temperature;
	}

	public java.lang.Double getHumidity() {
		return this.humidity;
	}

	public void setHumidity(java.lang.Double humidity) {
		this.humidity = humidity;
	}

	public java.lang.Integer getHourOfDay() {
		return this.hourOfDay;
	}

	public void setHourOfDay(java.lang.Integer hourOfDay) {
		this.hourOfDay = hourOfDay;
	}

	public java.lang.Integer getDayOfWeek() {
		return this.dayOfWeek;
	}

	public void setDayOfWeek(java.lang.Integer dayOfWeek) {
		this.dayOfWeek = dayOfWeek;
	}

	public java.lang.Integer getMonthOfYear() {
		return this.monthOfYear;
	}

	public void setMonthOfYear(java.lang.Integer monthOfYear) {
		this.monthOfYear = monthOfYear;
	}

	public java.lang.String getShift() {
		return this.shift;
	}

	public void setShift(java.lang.String shift) {
		this.shift = shift;
	}

	public SensorReading(java.lang.String sensorId,
			java.lang.String locationId, java.lang.Double pm25,
			java.util.Date ts, java.lang.Double pm1, java.lang.Double pm10,
			java.lang.Double temperature, java.lang.Double humidity,
			java.lang.Integer hourOfDay, java.lang.Integer dayOfWeek,
			java.lang.Integer monthOfYear, java.lang.String shift) {
		this.sensorId = sensorId;
		this.locationId = locationId;
		this.pm25 = pm25;
		this.ts = ts;
		this.pm1 = pm1;
		this.pm10 = pm10;
		this.temperature = temperature;
		this.humidity = humidity;
		this.hourOfDay = hourOfDay;
		this.dayOfWeek = dayOfWeek;
		this.monthOfYear = monthOfYear;
		this.shift = shift;
	}


    //   @org.kie.api.definition.type.Label(value = "co3")
	// private java.lang.Double co3;

	public java.lang.Double getCo3() {
			return this.co3;
	}

	public void setCo3(java.lang.Double co3) {
			this.co3 = co3;
	}

        public java.lang.Double getCo4() {
                return this.co4;
        }

        public void setCo4(java.lang.Double co4) {
                this.co4 = co4;
        }

}