package com.myspace.pollution.pollution_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SensorReading implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SensorReading() {
    }




}